package cn.itcast.domain.company;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Company implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.expiration_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date expirationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.license_id
     *
     * @mbg.generated
     */
    private String licenseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.representative
     *
     * @mbg.generated
     */
    private String representative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.company_size
     *
     * @mbg.generated
     */
    private String companySize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.balance
     *
     * @mbg.generated
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_company.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.id
     *
     * @return the value of ss_company.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.id
     *
     * @param id the value for ss_company.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.name
     *
     * @return the value of ss_company.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.name
     *
     * @param name the value for ss_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.expiration_date
     *
     * @return the value of ss_company.expiration_date
     *
     * @mbg.generated
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.expiration_date
     *
     * @param expirationDate the value for ss_company.expiration_date
     *
     * @mbg.generated
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.address
     *
     * @return the value of ss_company.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.address
     *
     * @param address the value for ss_company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.license_id
     *
     * @return the value of ss_company.license_id
     *
     * @mbg.generated
     */
    public String getLicenseId() {
        return licenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.license_id
     *
     * @param licenseId the value for ss_company.license_id
     *
     * @mbg.generated
     */
    public void setLicenseId(String licenseId) {
        this.licenseId = licenseId == null ? null : licenseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.representative
     *
     * @return the value of ss_company.representative
     *
     * @mbg.generated
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.representative
     *
     * @param representative the value for ss_company.representative
     *
     * @mbg.generated
     */
    public void setRepresentative(String representative) {
        this.representative = representative == null ? null : representative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.phone
     *
     * @return the value of ss_company.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.phone
     *
     * @param phone the value for ss_company.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.company_size
     *
     * @return the value of ss_company.company_size
     *
     * @mbg.generated
     */
    public String getCompanySize() {
        return companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.company_size
     *
     * @param companySize the value for ss_company.company_size
     *
     * @mbg.generated
     */
    public void setCompanySize(String companySize) {
        this.companySize = companySize == null ? null : companySize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.industry
     *
     * @return the value of ss_company.industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.industry
     *
     * @param industry the value for ss_company.industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.remarks
     *
     * @return the value of ss_company.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.remarks
     *
     * @param remarks the value for ss_company.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.state
     *
     * @return the value of ss_company.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.state
     *
     * @param state the value for ss_company.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.balance
     *
     * @return the value of ss_company.balance
     *
     * @mbg.generated
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.balance
     *
     * @param balance the value for ss_company.balance
     *
     * @mbg.generated
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.city
     *
     * @return the value of ss_company.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.city
     *
     * @param city the value for ss_company.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_company.is_delete
     *
     * @return the value of ss_company.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_company.is_delete
     *
     * @param isDelete the value for ss_company.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}